name: licence compliance

on: [push]

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Advance Security Compliance Action
        uses: GeekMasher/advanced-security-compliance@v1.6
        with:
          policy: GeekMasher/security-queries
          policy-path: policies/default.yml

          token: ${{ secrets.GITHUB_TOKEN  }}

          argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'
